services:
  railway:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./examples:/app/examples
      - ./output:/app/output
    stdin_open: true
    tty: true



#docker compose run railway 